version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.6.2
    networks:
      - kafka-net
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server1:
    container_name: kafka-server1
    image: bitnami/kafka:2.3.0
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  influxdb:
    container_name: influxdb
    image: influxdb:1.7-alpine
    networks:
      - kafka-net
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=db0
  kafka-pixy:
    container_name: kafka-pixy
    image: yashmeh/kafka-pixy:1
    networks:
      - kafka-net
    ports:
      - "19091:19091"
      - "19092:19092"
    volumes:
      - $PWD/kafka-pixy/kafka-pixy.yaml:/etc/kafka-pixy.yaml
    restart: always
    depends_on:
      - zookeeper
      - kafka-server1
      - influxdb
      - connector
    command: --config /etc/kafka-pixy.yaml
  connector:
    container_name: connector
    image: timberio/vector:nightly-alpine
    networks:
      - kafka-net
    ports:
      - "8383:8383"
    volumes:
      - $PWD/vector/vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      - influxdb
      - kafka-server1
networks:
  kafka-net:
volumes:
  influxdb:
